[package]
name = "notebook"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nanoid = "0.4.0"
tracing-subscriber = "0.3"
rustpython-parser = "0.2.0"
num-bigint = "0.4.3"
